<?php
/**
 * @file
 * Code for the SOD Users feature.
 */

include_once 'sod_users.features.inc';

/**
 * Implementation of hook_field_widget_form_alter()
 */
function sod_users_field_widget_form_alter(&$element, &$form_state, $context) {
  // hide addressfield elements #3372
  $fields = array('field_profiles_address_citta', 'field_profile_dove_vivo');
  if (in_array($element['#field_name'], $fields)) {
    $element['#process'][] = 'sod_users_addressfield_processing';
  }
}

/**
 * field_profile_address field processing
 */
function sod_users_addressfield_processing($element, &$form_state, $complete_form) {
  unset($element['street_block']);
  unset($element['locality_block']['postal_code']);
  return $element;
}


/**
 * Implements of hook_admin_paths()
 */
function sod_users_admin_paths() {
  $paths = array(
    'user/*/cancel' => TRUE,
    'user/*/edit' => TRUE,
    'user/*/edit/*' => TRUE,
  );
  return $paths;
}

/**
 * Implements hook_leaflet_map_info().
 *
 *
 */
function sod_users_leaflet_map_info() {
  $default_settings = array(
    'attributionControl' => TRUE,
    'closePopupOnClick'  => TRUE,
    'doubleClickZoom'    => TRUE,
    'dragging'           => TRUE,
    'fadeAnimation'      => TRUE,
    'layerControl'       => FALSE,
    'maxZoom'            => 18,
    'minZoom'            => 0,
    'scrollWheelZoom'    => TRUE,
    'touchZoom'          => TRUE,
    'trackResize'        => TRUE,
    // Don't specify, if you want to use Auto-box.
    // 'zoom'               =>  2,
    'zoomAnimation'      => TRUE,
    'zoomControl'        => TRUE,
  );

  $prot = '//';
  $zxy = '{z}/{x}/{y}.png';
  $attr_mapbox = 'Tiles by <a target="attr" href="http://mapbox.com">MapBox</a>. Map data &copy; <a href="http://openstreetap.org">OpenStreetMap</a> and contributors';

  $code = 'tmcw';
  $label = "MapBox tmcw (zoom 0..17)";
  $url_template = $prot . "{s}.tiles.mapbox.com/v3/tmcw.map-7s15q36b/$zxy";
  $map_info["mapbox-$code"] = array(
    'label' => 'Mapbox tmcw',
    'description' => $label,
    'settings' => array('maxZoom' => 17) + $default_settings,
    'layers' => array(
      'layer' => array(
        'urlTemplate' => $url_template,
        'options' => array('attribution' => $attr_mapbox),
      ),
    ),
  );
  return $map_info;
}

