<?php
/**
 * @file
 * Code for the SOD Users feature.
 */

include_once 'sod_users.features.inc';

/**
 * Implementation of hook_field_widget_form_alter()
 */
function sod_users_field_widget_form_alter(&$element, &$form_state, $context) {
  // hide addressfield elements #3372
  $fields = array('field_profiles_address_citta', 'field_profile_dove_vivo');
  if (in_array($element['#field_name'], $fields)) {
    $element['#process'][] = 'sod_users_addressfield_processing';
  }
}

/**
 * field_profile_address field processing
 */
function sod_users_addressfield_processing($element, &$form_state, $complete_form) {
  unset($element['street_block']);
  unset($element['locality_block']['postal_code']);
  return $element;
}


/**
 * Implements of hook_admin_paths()
 */
function sod_users_admin_paths() {
  $paths = array(
    'user/*/cancel' => TRUE,
    'user/*/edit' => TRUE,
    'user/*/edit/*' => TRUE,
  );
  return $paths;
}

/**
 * Implements hook_leaflet_map_prebuild_alter().
 */
function sod_users_leaflet_map_prebuild_alter(&$vars = NULL) {
  die('qui');
}
