<?php
/**
 * @file
 * Code for the sod_base feature.
 */

include_once('sod_base.features.inc');

/**
 * Implements hook_menu_block_blocks().
 */
function sod_base_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'custom-1' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Menu principale secondo livello',
      'level'       => 2,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}

/**
 * Implements of hook_block_view_alter()
 */
function sod_base_block_view_alter(&$data, $block) {
  if ($block->delta == 'powered-by') {
    $content = str_replace('</span>', ' ', $data['content']);
    $content .= 'e sviluppato da <a href="http://www.twinbit.it" target="_blank"> Twinbit </a> </span>';
    $data['content'] = $content;
  }
}
